### ISSUE TITLE
Package managers manifest parser  / Question

### ISSUE THREAD

**Issue by roscopecoltran** [bblfsh/bblfshd#142]
Hi,

Hope you are all well !

Goal: generate a source code summary by parsing source code and package manager manifests.

I was wondering if the project would be suitable to parse CMakeLists.txt or other dependencies manager (NPM, Maven,...) in order to get a more complete overview of any project. And how would be the best approach to do it.

Example of use case:
- Parse hunter packages (CMake based) for C++ repositories (https://github.com/ruslo/hunter)

Thanks in advance for any insights or point of view.

Cheers,

**Comment by mcuadros** [comment]
The current scope of bblfsh, doesn't include any manifest analysis. Since the implementation is focused on do analyze on file basis,  doesn't fit very well with the concept.

In the other hand we are planing on create another project or bblfsh component with a higer level of abstration and maybe the manifest analysis could fit there.

For doing manifest anlysis you can take a look to: https://github.com/librariesio/bibliothecary, a libraries create to do manifest parsing for Ruby. Doesn't work with CMake, but supports many other manifests.
