### ISSUE TITLE
Periodically update image with pre-installed drivers

### ISSUE THREAD

**Issue by lwsanty** [bblfsh/bblfshd#309]
### Pre-history
Currently we build docker image with all pre-installed drivers only when travis ci is triggered(on per-commit to master basis)

Thus we skip new driver versions until the next ci trigger for `bblfshd`

### Proposal
Add [cron job](https://docs.travis-ci.com/user/cron-jobs/) to `bblfshd`'s travis ci so we will have an ability to update drivers once in a period

### Problems
- _is not set up in config, so we need to file an issue to infra and mention desired period_
- _what should we do if no changes detected?_ IMO we can allow travis to run on the repo with no changes in drivers since the prev time, because in case of the same images the won't be pushed.

**Comment by dennwc** [comment]
This makes a lot of sense, but we should also think about a few more things:
- If we always update builtin drivers, it won't be possible for anymore to lock `bblfshd` version with a specific versions of builtin drivers. Maybe we can come up with some tag naming scheme to cover both `bblfshd` version and drivers? (`x.y.z-drivers-2019-09`?)
- When updating, we should probably reuse existing `bblfshd` image and install drivers over it, instead of rebuilding `bblfshd` again. This will make sure the change is incremental in regards to Docker layers.

**Comment by lwsanty** [comment]
@vmarkovtsev wdyt about @dennwc 's comment, will it be useful for ML team?

**Comment by vmarkovtsev** [comment]
As long as there is a tag which includes both the bblfshd version and the drivers date, it should be fine.

Speaking about us, we always install the drivers manually and choose only those which we need. We could switch to the full image if it is updated regularly.

**Comment by lwsanty** [comment]
need to wait for ttps://github.com/src-d/infrastructure/issues/1203 until changes start to work

**Comment by dpordomingo** [comment]
I know this is already closed, but found when bumping `sourced-ce` with the new `v2.16.1-drivers` release:
Did you consider to release, with the cron-ed release, an extra `v2.16.1-drivers-latest` one?

**Comment by ncordon** [comment]
I think this is related: #329
